spring:
  application:
    name: service-order
  profiles:
    active: dev #激活指定环境
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: ${spring.profiles.active:dev}
      config:
        namespace: ${spring.profiles.active:dev}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order


server:
  port: 8000

logging:
  level:
    com.atguigu.order.feign.ProductFeignClient: debug
feign:
  sentinel:
    enabled: true
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: sit

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: uat

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: prod