spring:
  application:
    name: gateway
  profiles:
    active: dev
    include: route
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: ${spring.profiles.active:dev}
#      config:
#        namespace: ${spring.profiles.active:dev}
#        import-check:
#          enabled: false

server:
  port: 80