spring:
  application:
    name: service-product
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: ${spring.profiles.active:dev}
      config:
        namespace: ${spring.profiles.active:dev}
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

server:
  port: 9000

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: sit

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: uat

---
spring:
  config:
    import:
      - nacos:common.properties?group=product
    activate:
      on-profile: prod